# General configuration
output_root: '../'
pytorch_data_dir: '/datadrive/pytorch-data/'
experiment_name: "exp1"
log_dir: "cocostuff27"
azureml_logging: True
submitting_to_aml: False

# Loader parameters
num_workers: 24
max_steps: 5000
batch_size: 16

# Dataset parameters
num_neighbors: 7
dataset_name: "cocostuff27"
dir_dataset_name: ~
dir_dataset_n_classes: 5
has_labels: False
crop_type: "five"
crop_ratio: 0.5
res: 224
loader_crop_type: "center"

# Model parameters
extra_clusters: 0
use_true_labels: False
use_recalibrator: False
model_type: "vit_small"
arch: "dino"
use_fit_model: False
dino_feat_type: "feat"
projection_type: "nonlinear"
dino_patch_size: 8
granularity: 1
continuous: True
dim: 70
dropout: True
zero_clamp: True
pretrained_weights: ~
use_salience: False
stabalize: False
stop_at_zero: True

# Learning rate and optimizer parameters
lr: 5e-4
optimizer:
  type: adam
  weight_decay: 0.0001

# Feature Contrastive parameters
pointwise: True
feature_samples: 11
neg_samples: 5
aug_alignment_weight: 0.0
correspondence_weight: 1.0

# Weights for different losses
neg_inter_weight: 0.63
pos_inter_weight: 0.25
pos_intra_weight: 0.67
neg_inter_shift: 0.46
pos_inter_shift: 0.12
pos_intra_shift: 0.18

# Reconstruction and repulsion weights
rec_weight: 0.0
repulsion_weight: 0.0

# CRF parameters
crf_weight: 0.0
alpha: 0.5
beta: 0.15
gamma: 0.05
w1: 10.0
w2: 3.0
shift: 0.00
crf_samples: 1000
color_space: "rgb"

# Logging parameters
reset_probe_steps: ~
n_images: 5
scalar_log_freq: 10
checkpoint_freq: 50
val_freq: 100
hist_freq: 100

# Hydra configuration
hydra:
  run:
    dir: "."
  output_subdir: ~
